name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Deploy react to gh-pages
        run: npm run deploy
